#!/bin/sh
#
# Writes the C header holding this build's version notes: the subject line of
# every commit made after the last published package. The makefile generates it
# into release/generated/ on every build and src/versionnotes.c compiles it in,
# which is what lets the UI's "Version notes" window say what is new in the
# uvcan the user is running -- a published binary carries its own release notes
# instead of asking anyone to go and read the repository.
#
#   gen-version-notes.sh <manifest> <build id>       > header
#
# <manifest> is ../prod/latest.json, the manifest 'make update-manifest' wrote
# when the last package was published, and <build id> is this build's
# __UV_PROGRAM_VERSION (git rev-list --count HEAD). The commits between the two
# are exactly what this build adds to what was published.
#
# The manifest is not tracked (prod/ is ignored), so it is there on the machine
# that publishes -- the one whose builds are shipped and the only one whose
# notes anybody reads -- and missing on a fresh clone. Without it the last
# published build cannot be known, so the notes fall back to the newest handful
# of commits and say so by reporting the build they start from as 0.

set -eu

MANIFEST="${1:-}"
BUILD="${2:-0}"

# Most commits listed. A release is a handful of them; the cap is only here so a
# build made long after the last published one cannot grow the binary without
# bound.
MAX_NOTES=500
# What a build with no manifest lists instead (see above).
UNKNOWN_NOTES=20
# Longest subject kept, in characters. Longer ones are cut with an ellipsis: the
# window wraps what it is given, but a commit that wrote a paragraph into its
# subject line would fill the window with one note.
MAX_TEXT=200


since_build=0
since_name=""
if [ -f "$MANIFEST" ]; then
	# Read with sed rather than a JSON parser: this exact file is written by the
	# makefile's update-manifest target, one field per line, and a build must not
	# depend on jq being installed.
	since_build=$(sed -n \
		's/^[[:space:]]*"version"[[:space:]]*:[[:space:]]*\([0-9][0-9]*\).*/\1/p' \
		"$MANIFEST" | head -n 1)
	since_name=$(sed -n \
		's/^[[:space:]]*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
		"$MANIFEST" | head -n 1)
	[ -n "$since_build" ] || since_build=0
fi

# The published version's name is "<build>-g<hash>", so it names the commit the
# package was built from: asking git for what came after that commit is exact,
# and it stays exact whatever anybody has done to the branch since. The commit
# counts are the fallback for a hash this clone does not have (a package built
# from a branch that was since rewritten): build ids are commit counts, so their
# difference is how many commits are new.
hash=""
case "$since_name" in
	*-g*) hash=${since_name##*-g} ;;
esac
# a "-dirty" build should never have been published, but do not let one turn
# into a bogus revision name here
hash=${hash%%-*}

if [ -n "$hash" ] && git rev-parse -q --verify "$hash^{commit}" >/dev/null 2>&1; then
	set -- "$hash..HEAD"
elif [ "$since_build" -gt 0 ]; then
	count=$(( BUILD - since_build ))
	if [ "$count" -lt 0 ]; then
		count=0
	fi
	set -- -n "$count" HEAD
else
	set -- -n "$UNKNOWN_NOTES" HEAD
	since_build=0
	since_name=""
fi

# --no-merges: a merge commit's subject says which branch was merged, which is
# not a change anybody released. With the commit-count fallback above this can
# reach one commit further back per merge in the range; the exact path does not.
notes=$(git log --no-merges --date=short --format='%ad|%s' "$@" 2>/dev/null || true)

total=0
if [ -n "$notes" ]; then
	total=$(printf '%s\n' "$notes" | wc -l | tr -d ' ')
fi
truncated=0
if [ "$total" -gt "$MAX_NOTES" ]; then
	notes=$(printf '%s\n' "$notes" | head -n "$MAX_NOTES")
	truncated=$(( total - MAX_NOTES ))
	total=$MAX_NOTES
fi

printf '/* Generated by packaging/gen-version-notes.sh -- do not edit.\n'
printf ' *\n'
printf ' * The subject line of every commit made after the last published\n'
printf ' * package, newest first: what this build adds to what was published.\n'
printf ' * Included by src/versionnotes.c, which defines versionnote_st.\n'
printf ' */\n'
printf '#ifndef UVCAN_VERSIONNOTES_GEN_H_\n'
printf '#define UVCAN_VERSIONNOTES_GEN_H_\n'
printf '\n'
printf '/* The published build these notes start after, 0 when it is not known. */\n'
printf '#define VERSION_NOTES_SINCE_BUILD\t%s\n' "$since_build"
printf '#define VERSION_NOTES_SINCE_NAME\t"%s"\n' "$since_name"
printf '/* Commits left out of the list below, over the cap it is kept under. */\n'
printf '#define VERSION_NOTES_OMITTED\t\t%s\n' "$truncated"
printf '#define VERSION_NOTES_COUNT\t\t\t%s\n' "$total"
printf '\n'
printf '/* One entry per commit, plus a terminating empty one: an array with no\n'
printf ' * elements at all is not C, and a build with nothing new has none. */\n'
printf 'static const versionnote_st version_notes[VERSION_NOTES_COUNT + 1] = {\n'
if [ -n "$notes" ]; then
	printf '%s\n' "$notes" | while IFS= read -r line; do
		date=${line%%|*}
		text=${line#*|}
		# cut an overlong subject on a character boundary, then escape what a C
		# string cannot hold as it stands
		text=$(printf '%s' "$text" | cut -c "1-$MAX_TEXT")
		if [ "${#text}" -ge "$MAX_TEXT" ]; then
			text="$text..."
		fi
		text=$(printf '%s' "$text" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')
		printf '\t{ "%s", "%s" },\n' "$date" "$text"
	done
fi
printf '\t{ "", "" }\n'
printf '};\n'
printf '\n'
printf '#endif /* UVCAN_VERSIONNOTES_GEN_H_ */\n'
