/*
 * uw_hal_config.h
 *
 *  Created on: Mar 22, 2016
 *      Author: usevolt
 */

#ifndef UV_HAL_CONFIG_H_
#define UV_HAL_CONFIG_H_


/**** USER CONFIGURATIONS ****/


#define CONFIG_TARGET_LPC11C14			0
#define CONFIG_TARGET_LPC1785			0
#define CONFIG_TARGET_LPC1549			0
#define CONFIG_TARGET_LINUX				1



#define CONFIG_INTERFACE_REVISION		1



#define CONFIG_NON_VOLATILE_MEMORY		1
#define CONFIG_MAIN_H					"main.h"
#define CONFIG_APP_ST					struct _dev_st dev
#define CONFIG_NON_VOLATILE_START		dev.data_start
#define CONFIG_NON_VOLATILE_END			dev.data_end



#define CONFIG_RTOS						1
#define CONFIG_RTOS_HEAP_SIZE			1000000
#define CONFIG_UV_BOOTLOADER			1


#define CONFIG_PWM						0
#define CONFIG_PWM0						0
#define CONFIG_PWM0_FREQ				200
#define CONFIG_PWM0_0					1
#define CONFIG_PWM0_0_IO				P0_4
#define CONFIG_PWM0_4					0
#define CONFIG_PWM0_4_IO				0

#define CONFIG_PWM1						0
#define CONFIG_PWM1_FREQ				10000


#define CONFIG_UART0					0

#define CONFIG_UART1					0

#define CONFIG_UART2					0

#define CONFIG_UART3					0

#define CONFIG_UART4					0







#define CONFIG_TERMINAL					0
#define CONFIG_TERMINAL_BUFFER_SIZE		200
#define CONFIG_TERMINAL_ARG_COUNT		4
#define CONFIG_TERMINAL_INSTRUCTIONS	1
#define CONFIG_TERMINAL_UART			0
#define CONFIG_TERMINAL_CAN				0
#define CONFIG_TERMINAL_CLI				1





#define CONFIG_ADC0						0
#define CONFIG_ADC1						0
#define CONFIG_ADC_MODE					ADC_MODE_SYNC
#define CONFIG_ADC_CONVERSION_FREQ		20000

#define CONFIG_ADC_CHANNEL0_0			0
#define CONFIG_ADC_CHANNEL0_1			0
#define CONFIG_ADC_CHANNEL0_2			0
#define CONFIG_ADC_CHANNEL0_3			0
#define CONFIG_ADC_CHANNEL0_4			0
#define CONFIG_ADC_CHANNEL0_5			0
#define CONFIG_ADC_CHANNEL0_6			0
#define CONFIG_ADC_CHANNEL0_7			0
#define CONFIG_ADC_CHANNEL0_8			0
#define CONFIG_ADC_CHANNEL0_9			0
#define CONFIG_ADC_CHANNEL0_10			0
#define CONFIG_ADC_CHANNEL0_11			0
#define CONFIG_ADC_CHANNEL1_0			0
#define CONFIG_ADC_CHANNEL1_1			0
#define CONFIG_ADC_CHANNEL1_2			0
#define CONFIG_ADC_CHANNEL1_3			0
#define CONFIG_ADC_CHANNEL1_4			0
#define CONFIG_ADC_CHANNEL1_5			0
#define CONFIG_ADC_CHANNEL1_6			0
#define CONFIG_ADC_CHANNEL1_7			0
#define CONFIG_ADC_CHANNEL1_8			0
#define CONFIG_ADC_CHANNEL1_9			0
#define CONFIG_ADC_CHANNEL1_10			0
#define CONFIG_ADC_CHANNEL1_11			0









#define CONFIG_CAN							1
#define CONFIG_CAN0							0
#define CONFIG_CAN1							0
#define CONFIG_SOCKETCAN					1
#define CONFIG_CAN_LOG						0
#define CONFIG_CAN_ERROR_LOG				0


#define CONFIG_CANOPEN								0
#define CONFIG_CANOPEN_LOG							0
#define CONFIG_CANOPEN_RXPDO_COUNT					1
#define CONFIG_CANOPEN_TXPDO_COUNT					1
#define CONFIG_CANOPEN_PDO_MAPPING_COUNT			8
#define CONFIG_CANOPEN_SDO_SYNC						1
#define CONFIG_CANOPEN_SDO_SEGMENTED				0
#define CONFIG_CANOPEN_SDO_TIMEOUT_MS				10
#define CONFIG_CANOPEN_OBJ_DICT_APP_PARAMS			obj_dict
#define CONFIG_CANOPEN_OBJ_DICT_APP_PARAMS_COUNT	obj_dict_len
#define CONFIG_CANOPEN_PRODUCER_HEARTBEAT_TIME_MS	1000
#define CONFIG_CANOPEN_CONSUMER_HEARTBEAT_COUNT		0
#define CONFIG_CANOPEN_CHANNEL						CAN0
#define CONFIG_CANOPEN_DEFAULT_NODE_ID				ESB_NODE_ID
#define CONFIG_CANOPEN_EMCY_RX_BUFFER_SIZE			3

#define CONFIG_CANOPEN_RXPDO1_ID					(CANOPEN_TXPDO1_ID + 1)
#define CONFIG_CANOPEN_RXPDO1_TRANSMISSION_TYPE		CANOPEN_PDO_TRANSMISSION_ASYNC
#define CONFIG_CANOPEN_RXPDO1_MAPPING1_MAIN_INDEX	0
#define CONFIG_CANOPEN_RXPDO1_MAPPING1_SUB_INDEX	0
#define CONFIG_CANOPEN_RXPDO1_MAPPING1_LEN			CANOPEN_TYPE_LEN(FSB_TOTAL_CURRENT_TYPE)
#define CONFIG_CANOPEN_RXPDO1_MAPPING2_MAIN_INDEX	ESB_FSB_IGNKEY_INDEX
#define CONFIG_CANOPEN_RXPDO1_MAPPING2_SUB_INDEX	ESB_FSB_IGNKEY_SUBINDEX
#define CONFIG_CANOPEN_RXPDO1_MAPPING2_LEN			CANOPEN_TYPE_LEN(ESB_FSB_IGNKEY_TYPE)
#define CONFIG_CANOPEN_RXPDO1_MAPPING3_MAIN_INDEX	ESB_FSB_EMCY_INDEX
#define CONFIG_CANOPEN_RXPDO1_MAPPING3_SUB_INDEX	ESB_FSB_EMCY_SUBINDEX
#define CONFIG_CANOPEN_RXPDO1_MAPPING3_LEN			CANOPEN_TYPE_LEN(ESB_FSB_EMCY_TYPE)
#define CONFIG_CANOPEN_RXPDO1_MAPPING4_MAIN_INDEX	0
#define CONFIG_CANOPEN_RXPDO1_MAPPING4_SUB_INDEX	0
#define CONFIG_CANOPEN_RXPDO1_MAPPING4_LEN			0
#define CONFIG_CANOPEN_RXPDO1_MAPPING5_MAIN_INDEX	0
#define CONFIG_CANOPEN_RXPDO1_MAPPING5_SUB_INDEX	0
#define CONFIG_CANOPEN_RXPDO1_MAPPING5_LEN			0
#define CONFIG_CANOPEN_RXPDO1_MAPPING6_MAIN_INDEX	0
#define CONFIG_CANOPEN_RXPDO1_MAPPING6_SUB_INDEX	0
#define CONFIG_CANOPEN_RXPDO1_MAPPING6_LEN			0
#define CONFIG_CANOPEN_RXPDO1_MAPPING7_MAIN_INDEX	0
#define CONFIG_CANOPEN_RXPDO1_MAPPING7_SUB_INDEX	0
#define CONFIG_CANOPEN_RXPDO1_MAPPING7_LEN			0
#define CONFIG_CANOPEN_RXPDO1_MAPPING8_MAIN_INDEX	0
#define CONFIG_CANOPEN_RXPDO1_MAPPING8_SUB_INDEX	0
#define CONFIG_CANOPEN_RXPDO1_MAPPING8_LEN			0


#define CONFIG_CANOPEN_TXPDO1_ID					(CANOPEN_TXPDO1_ID + 1)
#define CONFIG_CANOPEN_TXPDO1_TRANSMISSION_TYPE		CANOPEN_PDO_TRANSMISSION_ASYNC
#define CONFIG_CANOPEN_TXPDO1_EVENT_TIMER			200
#define CONFIG_CANOPEN_TXPDO1_MAPPING1_MAIN_INDEX	ESB_TOTAL_CURRENT_INDEX
#define CONFIG_CANOPEN_TXPDO1_MAPPING1_SUB_INDEX	ESB_TOTAL_CURRENT_SUBINDEX
#define CONFIG_CANOPEN_TXPDO1_MAPPING1_LEN			CANOPEN_TYPE_LEN(ESB_TOTAL_CURRENT_TYPE)
#define CONFIG_CANOPEN_TXPDO1_MAPPING2_MAIN_INDEX	ESB_RPM_INDEX
#define CONFIG_CANOPEN_TXPDO1_MAPPING2_SUB_INDEX	ESB_RPM_SUBINDEX
#define CONFIG_CANOPEN_TXPDO1_MAPPING2_LEN			CANOPEN_TYPE_LEN(ESB_RPM_TYPE)
#define CONFIG_CANOPEN_TXPDO1_MAPPING3_MAIN_INDEX	ESB_ALT_L_INDEX
#define CONFIG_CANOPEN_TXPDO1_MAPPING3_SUB_INDEX	ESB_ALT_L_SUBINDEX
#define CONFIG_CANOPEN_TXPDO1_MAPPING3_LEN			CANOPEN_TYPE_LEN(ESB_ALT_L_TYPE)
#define CONFIG_CANOPEN_TXPDO1_MAPPING4_MAIN_INDEX	ESB_MOTOR_WATER_TEMP_INDEX
#define CONFIG_CANOPEN_TXPDO1_MAPPING4_SUB_INDEX	ESB_MOTOR_WATER_TEMP_SUBINDEX
#define CONFIG_CANOPEN_TXPDO1_MAPPING4_LEN			CANOPEN_TYPE_LEN(ESB_MOTOR_WATER_TEMP_TYPE)
#define CONFIG_CANOPEN_TXPDO1_MAPPING5_MAIN_INDEX	ESB_MOTOR_OIL_PRESS_INDEX
#define CONFIG_CANOPEN_TXPDO1_MAPPING5_SUB_INDEX	ESB_MOTOR_OIL_PRESS_SUBINDEX
#define CONFIG_CANOPEN_TXPDO1_MAPPING5_LEN			CANOPEN_TYPE_LEN(ESB_MOTOR_OIL_PRESS_TYPE)
#define CONFIG_CANOPEN_TXPDO1_MAPPING6_MAIN_INDEX	0
#define CONFIG_CANOPEN_TXPDO1_MAPPING6_SUB_INDEX	0
#define CONFIG_CANOPEN_TXPDO1_MAPPING6_LEN			0
#define CONFIG_CANOPEN_TXPDO1_MAPPING7_MAIN_INDEX	0
#define CONFIG_CANOPEN_TXPDO1_MAPPING7_SUB_INDEX	0
#define CONFIG_CANOPEN_TXPDO1_MAPPING7_LEN			0
#define CONFIG_CANOPEN_TXPDO1_MAPPING8_MAIN_INDEX	0
#define CONFIG_CANOPEN_TXPDO1_MAPPING8_SUB_INDEX	0
#define CONFIG_CANOPEN_TXPDO1_MAPPING8_LEN			0



#define CONFIG_OUTPUT								0

#define CONFIG_SOLENOID_OUTPUT						0
#define CONFIG_SOLENOID_P							10
#define CONFIG_SOLENOID_I							0

#define CONFIG_PID									0

/**** END OF USER CONFIGURATIONS ****/




#endif /* UV_HAL_CONFIG_H_ */
